services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    ports: [ "5432:5432" ]
    volumes: [ "pg:/var/lib/postgresql/data" ]

  redis:
    image: redis:7
    ports: [ "6379:6379" ]

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: [ "9000:9000", "9001:9001" ]
    volumes: [ "minio:/data" ]

  clickhouse:
    image: clickhouse/clickhouse-server:24
    ports: [ "9002:9000" ]

  nats:
    image: nats:2.10
    command: ["-js"]
    ports: [ "4222:4222" ]

  temporal:
    image: temporalio/auto-setup:1.25
    environment:
      DB: postgresql
      POSTGRES_USER: postgres
      POSTGRES_PWD: postgres
      POSTGRES_SEEDS: postgres
    ports: [ "7233:7233" ]

  keycloak:
    image: quay.io/keycloak/keycloak:24
    command: ["start-dev", "--http-port=8080"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports: [ "8080:8080" ]

volumes:
  pg: {}
  minio: {}